### ISSUE TITLE
`require "em/pure_ruby"` in Gemfile caused bundler to freak out

### ISSUE THREAD

**Issue by bjork24** [bpainter/blendconf.com#28]
Using rbenv, [`require "em/pure_ruby"`](https://github.com/bpainter/blendconf.com/blob/master/Gemfile#L16) throws the following error:

```
$  bundle install
/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- em/pure_ruby (LoadError)
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
       /Users/dan/Dropbox/dev/blendconf.com/Gemfile:16:in `eval_gemfile'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/dsl.rb:32:in `instance_eval'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/dsl.rb:32:in `eval_gemfile'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/dsl.rb:10:in `evaluate'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/definition.rb:25:in `build'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler.rb:155:in `definition'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/cli/install.rb:77:in `run'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/cli.rb:145:in `install'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/command.rb:27:in `run'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/vendor/thor.rb:363:in `dispatch'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/base.rb:440:in `start'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/cli.rb:9:in `start'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/bin/bundle:20:in `block in <top (required)>'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
       /Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.7.12/bin/bundle:18:in `<top (required)>'
       /Users/dan/.rbenv/versions/2.0.0-p247/bin/bundle:23:in `load'
       /Users/dan/.rbenv/versions/2.0.0-p247/bin/bundle:23:in `<main>'
There was an error in your Gemfile, and Bundler cannot continue.
```

Not sure if this is Mac-specific or not, but commenting it out allows for bundler to continue.

**Comment by bjork24** [comment]
Actually, this is just on the master branch, which probably isn't relevant anymore. Feel free to close.
